export enum Languages {
  EN = "en",
  DE = "de",
  FR = "fr",
  PL = "pl",
  UA = "ua",
  RO = "ro",
  ES = "es",
  PT = "pt",
  IT = "it",
  NL = "nl",
  SE = "se",
  NO = "no",
  FI = "fi",
  DK = "dk",
  TR = "tr",
}

export const LANGUAGE_NAMES: Record<Languages, string> = {
  [Languages.EN]: "English",
  [Languages.DE]: "Deutsch",
  [Languages.FR]: "Français",
  [Languages.PL]: "Polski",
  [Languages.UA]: "Українська",
  [Languages.RO]: "Română",
  [Languages.ES]: "Español",
  [Languages.PT]: "Português",
  [Languages.IT]: "Italiano",
  [Languages.NL]: "Nederlands",
  [Languages.SE]: "Svenska",
  [Languages.NO]: "Norsk",
  [Languages.FI]: "Suomi",
  [Languages.DK]: "Dansk",
  [Languages.TR]: "Türkçe",
};

export const LANGUAGE_FLAGS: Record<Languages, string> = {
  [Languages.EN]: "GB",
  [Languages.DE]: "DE",
  [Languages.FR]: "FR",
  [Languages.PL]: "PL",
  [Languages.UA]: "UA",
  [Languages.RO]: "RO",
  [Languages.ES]: "ES",
  [Languages.PT]: "PT",
  [Languages.IT]: "IT",
  [Languages.NL]: "NL",
  [Languages.SE]: "SE",
  [Languages.NO]: "NO",
  [Languages.FI]: "FI",
  [Languages.DK]: "DK",
  [Languages.TR]: "TR",
};
